jenkins:
  image: accenturepdc/adop-jenkins:2-0.1.1
  environment:
    ADOP_GERRIT_ENABLED: "false"
    ADOP_GITLAB_ENABLED: "false"
    GIT_REPO: "gitlab"
    GITLAB_FRONT_END_URL: "http://gitlab/gitlab"
    GITLAB_JENKINS_USERNAME: "jenkins"
    GITLAB_JENKINS_PASSWORD: ${PASSWORD_JENKINS}
    GITLAB_ROOT_PASSWORD: ${PASSWORD_GITLAB}

proxy:
  image: pgilc/fmw-nginx:0.1.0
  environment:
    GIT_REPO: "gitlab"

jenkins-slave:
  environment:
    PASSWORD_GITLAB: "${PASSWORD_GITLAB}"
    PUBLIC_IP: "${PUBLIC_IP}"

