jenkins:
  image: accenturepdc/adop-jenkins:2-0.1.1
  environment:
    ADOP_GERRIT_ENABLED: "false"
    ADOP_GITLAB_ENABLED: "true"
    GIT_REPO: "gitlab"
    GITLAB_FRONT_END_URL: "http://gitlab/gitlab"
    GITLAB_JENKINS_USERNAME: "jenkins"
    GITLAB_JENKINS_PASSWORD: ${PASSWORD_JENKINS}
    GITLAB_ROOT_PASSWORD: ${PASSWORD_GITLAB}

proxy:
  image: accenturepdc/adop-nginx:0.1.0
  environment:
    GIT_REPO: "gitlab"

jenkins-slave:
  environment:
    PASSWORD_GITLAB: "${PASSWORD_GITLAB}"
    PUBLIC_IP: "${PUBLIC_IP}"

gitlab:
  container_name: gitlab
  restart: always
  image: gitlab/gitlab-ce:8.15.4-ce.1
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "80"
    - "443"
    - "22"
  volumes:
    - gitlab_etc:/etc/gitlab
    - gitlab_opt:/var/opt/gitlab
    - gitlab_log:/var/log/gitlab
  environment:
    GITLAB_ROOT_PASSWORD: ${PASSWORD_GITLAB}
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://${PUBLIC_IP}/gitlab'
      gitlab_rails['smtp_enable'] = '${ADOP_SMTP_ENABLED}'
      gitlab_rails['smtp_address'] = 'mail-server'
      gitlab_rails['smtp_port'] = 25
      gitlab_rails['smtp_user_name'] = '${INITIAL_ADMIN_USER}@${LDAP_DOMAIN}'
      gitlab_rails['smtp_password'] = '${INITIAL_ADMIN_PASSWORD_PLAIN}'
      gitlab_rails['smtp_domain'] = '${SMTP_DOMAIN}'
      gitlab_rails['smtp_authentication'] = 'login'
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
        main:
          label: 'LDAP'
          host: ldap
          port: 389
          uid: 'uid'
          method: 'plain'
          bind_dn: 'cn=admin,${LDAP_FULL_DOMAIN}'
          password: '${LDAP_PWD}'
          active_directory: false
          allow_username_or_email_login: false
          block_auto_created_users: false
          base: '${LDAP_FULL_DOMAIN}'
      EOS
