jenkins:
  environment:
    AWS_REGION: "${AWS_DEFAULT_REGION}"
    AWS_VPC_ID: "${AWS_VPC_ID}"
    AWS_VPC_CIDR: "${AWS_VPC_CIDR}"
    AWS_KEYPAIR: "${AWS_KEY_PAIR}"
    AWS_SUBNET_ID: "${AWS_PUBLIC_SUBNET_ID}"
    DEFAULT_PUBLIC_SUBNET_ID: "${AWS_PUBLIC_SUBNET_ID}"
    DEFAULT_PRIVATE_SUBNET_ID: "${AWS_PRIVATE_SUBNET_ID}"
    DEFAULT_RHEL_AMI: "${AWS_DEFAULT_RHEL_AMI}"
    DEFAULT_CENTOS_AMI: "${AWS_DEFAULT_CENTOS_AMI}"
    DEFAULT_AWS_LINUX_AMI: "${AWS_DEFAULT_AWS_LINUX_AMI}"

jenkins-slave:
  environment:
    AWS_REGION: "${AWS_DEFAULT_REGION}"
    AWS_VPC_ID: "${AWS_VPC_ID}"
    AWS_VPC_CIDR: "${AWS_VPC_CIDR}"
    AWS_KEYPAIR: "${AWS_KEY_PAIR}"
    AWS_SUBNET_ID: "${AWS_PUBLIC_SUBNET_ID}"
